nav:
  - !doc-nav-item
    link: /
    dir: /docs

  - !doc-nav-item
    link: /d3-basic/
    dir: /docs/d3-basic

  - !doc-nav-item
    link: /examples/
    dir: /docs/examples

  - text: d3js.org
    link: https://d3js.org/

  - text: d3.js API
    link: https://github.com/d3/d3/blob/master/API.md

sidebar:
  /d3-basic/:
    - !doc-category
      dir: /docs/d3-basic

  /examples/:
    - !doc-category
      dir: /docs/examples