nav:
  - !doc-nav-item
    link: /
    dir: /docs

  - !doc-nav-item
    link: /d3-basic/
    dir: /docs/d3-basic

  - !doc-nav-item
    link: /examples/
    dir: /docs/examples

  - text: d3js.org
    link: https://d3js.org/

sidebar:
  /d3-basic/:
    - !doc-category
      dir: /docs/d3-basic

resourcesMap:
  d3@5: "https://cdnjs.cloudflare.com/ajax/libs/d3/5.9.7/d3.min.js"
  d3@4: "https://cdnjs.cloudflare.com/ajax/libs/d3/4.13.0/d3.min.js"
  lodash@4: "https://cdnjs.cloudflare.com/ajax/libs/lodash.js/4.17.11/lodash.min.js"
  normalize-css: "https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.min.css"
