nav:
  - !doc-nav-item
    link: /
    dir: /docs

  - !doc-nav-item
    link: /d3-basic/
    dir: /docs/d3-basic

  - !doc-nav-item
    link: /examples/
    dir: /docs/examples

  - text: d3js.org
    link: https://d3js.org/

sidebar:
  /d3-basic/:
    - !doc-category
      dir: /docs/d3-basic
