js:
  - https://cdnjs.cloudflare.com/ajax/libs/d3/5.9.7/d3.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/lodash.js/4.17.11/lodash.min.js

css:
  - https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.min.css
